// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: peerseeds.proto

package org.flo.crawler;

public final class PeerSeedProtos {
  private PeerSeedProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface PeerSeedDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.flo.crawler.PeerSeedData)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required string ip_address = 1;</code>
     */
    boolean hasIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     */
    java.lang.String getIpAddress();
    /**
     * <code>required string ip_address = 1;</code>
     */
    com.google.protobuf.ByteString
        getIpAddressBytes();

    /**
     * <code>required uint32 port = 2;</code>
     */
    boolean hasPort();
    /**
     * <code>required uint32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>required uint32 services = 3;</code>
     */
    boolean hasServices();
    /**
     * <code>required uint32 services = 3;</code>
     */
    int getServices();
  }
  /**
   * Protobuf type {@code org.flo.crawler.PeerSeedData}
   */
  public  static final class PeerSeedData extends
      com.google.protobuf.GeneratedMessageLite<
          PeerSeedData, PeerSeedData.Builder> implements
      // @@protoc_insertion_point(message_implements:org.flo.crawler.PeerSeedData)
      PeerSeedDataOrBuilder {
    private PeerSeedData() {
      ipAddress_ = "";
    }
    private int bitField0_;
    public static final int IP_ADDRESS_FIELD_NUMBER = 1;
    private java.lang.String ipAddress_;
    /**
     * <code>required string ip_address = 1;</code>
     */
    public boolean hasIpAddress() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    public java.lang.String getIpAddress() {
      return ipAddress_;
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIpAddressBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(ipAddress_);
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    private void setIpAddress(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      ipAddress_ = value;
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    private void clearIpAddress() {
      bitField0_ = (bitField0_ & ~0x00000001);
      ipAddress_ = getDefaultInstance().getIpAddress();
    }
    /**
     * <code>required string ip_address = 1;</code>
     */
    private void setIpAddressBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      ipAddress_ = value.toStringUtf8();
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>required uint32 port = 2;</code>
     */
    public boolean hasPort() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    private void setPort(int value) {
      bitField0_ |= 0x00000002;
      port_ = value;
    }
    /**
     * <code>required uint32 port = 2;</code>
     */
    private void clearPort() {
      bitField0_ = (bitField0_ & ~0x00000002);
      port_ = 0;
    }

    public static final int SERVICES_FIELD_NUMBER = 3;
    private int services_;
    /**
     * <code>required uint32 services = 3;</code>
     */
    public boolean hasServices() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint32 services = 3;</code>
     */
    public int getServices() {
      return services_;
    }
    /**
     * <code>required uint32 services = 3;</code>
     */
    private void setServices(int value) {
      bitField0_ |= 0x00000004;
      services_ = value;
    }
    /**
     * <code>required uint32 services = 3;</code>
     */
    private void clearServices() {
      bitField0_ = (bitField0_ & ~0x00000004);
      services_ = 0;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeString(1, getIpAddress());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt32(3, services_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getIpAddress());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, port_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, services_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeedData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flo.crawler.PeerSeedProtos.PeerSeedData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code org.flo.crawler.PeerSeedData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.flo.crawler.PeerSeedProtos.PeerSeedData, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.flo.crawler.PeerSeedData)
        org.flo.crawler.PeerSeedProtos.PeerSeedDataOrBuilder {
      // Construct using org.flo.crawler.PeerSeedProtos.PeerSeedData.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required string ip_address = 1;</code>
       */
      public boolean hasIpAddress() {
        return instance.hasIpAddress();
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public java.lang.String getIpAddress() {
        return instance.getIpAddress();
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIpAddressBytes() {
        return instance.getIpAddressBytes();
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder setIpAddress(
          java.lang.String value) {
        copyOnWrite();
        instance.setIpAddress(value);
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder clearIpAddress() {
        copyOnWrite();
        instance.clearIpAddress();
        return this;
      }
      /**
       * <code>required string ip_address = 1;</code>
       */
      public Builder setIpAddressBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setIpAddressBytes(value);
        return this;
      }

      /**
       * <code>required uint32 port = 2;</code>
       */
      public boolean hasPort() {
        return instance.hasPort();
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public int getPort() {
        return instance.getPort();
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder setPort(int value) {
        copyOnWrite();
        instance.setPort(value);
        return this;
      }
      /**
       * <code>required uint32 port = 2;</code>
       */
      public Builder clearPort() {
        copyOnWrite();
        instance.clearPort();
        return this;
      }

      /**
       * <code>required uint32 services = 3;</code>
       */
      public boolean hasServices() {
        return instance.hasServices();
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public int getServices() {
        return instance.getServices();
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public Builder setServices(int value) {
        copyOnWrite();
        instance.setServices(value);
        return this;
      }
      /**
       * <code>required uint32 services = 3;</code>
       */
      public Builder clearServices() {
        copyOnWrite();
        instance.clearServices();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.flo.crawler.PeerSeedData)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.flo.crawler.PeerSeedProtos.PeerSeedData();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasIpAddress()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPort()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasServices()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.flo.crawler.PeerSeedProtos.PeerSeedData other = (org.flo.crawler.PeerSeedProtos.PeerSeedData) arg1;
          ipAddress_ = visitor.visitString(
              hasIpAddress(), ipAddress_,
              other.hasIpAddress(), other.ipAddress_);
          port_ = visitor.visitInt(
              hasPort(), port_,
              other.hasPort(), other.port_);
          services_ = visitor.visitInt(
              hasServices(), services_,
              other.hasServices(), other.services_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  String s = input.readString();
                  bitField0_ |= 0x00000001;
                  ipAddress_ = s;
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000002;
                  port_ = input.readUInt32();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  services_ = input.readUInt32();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.flo.crawler.PeerSeedProtos.PeerSeedData.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.flo.crawler.PeerSeedData)
    private static final org.flo.crawler.PeerSeedProtos.PeerSeedData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PeerSeedData();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.flo.crawler.PeerSeedProtos.PeerSeedData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PeerSeedData> PARSER;

    public static com.google.protobuf.Parser<PeerSeedData> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface PeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.flo.crawler.PeerSeeds)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    java.util.List<org.flo.crawler.PeerSeedProtos.PeerSeedData> 
        getSeedList();
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    org.flo.crawler.PeerSeedProtos.PeerSeedData getSeed(int index);
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    int getSeedCount();

    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    boolean hasTimestamp();
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    long getTimestamp();

    /**
     * <code>required string net = 3;</code>
     */
    boolean hasNet();
    /**
     * <code>required string net = 3;</code>
     */
    java.lang.String getNet();
    /**
     * <code>required string net = 3;</code>
     */
    com.google.protobuf.ByteString
        getNetBytes();
  }
  /**
   * Protobuf type {@code org.flo.crawler.PeerSeeds}
   */
  public  static final class PeerSeeds extends
      com.google.protobuf.GeneratedMessageLite<
          PeerSeeds, PeerSeeds.Builder> implements
      // @@protoc_insertion_point(message_implements:org.flo.crawler.PeerSeeds)
      PeerSeedsOrBuilder {
    private PeerSeeds() {
      seed_ = emptyProtobufList();
      net_ = "";
    }
    private int bitField0_;
    public static final int SEED_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<org.flo.crawler.PeerSeedProtos.PeerSeedData> seed_;
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    public java.util.List<org.flo.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
      return seed_;
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    public java.util.List<? extends org.flo.crawler.PeerSeedProtos.PeerSeedDataOrBuilder> 
        getSeedOrBuilderList() {
      return seed_;
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    public int getSeedCount() {
      return seed_.size();
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    public org.flo.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
      return seed_.get(index);
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    public org.flo.crawler.PeerSeedProtos.PeerSeedDataOrBuilder getSeedOrBuilder(
        int index) {
      return seed_.get(index);
    }
    private void ensureSeedIsMutable() {
      if (!seed_.isModifiable()) {
        seed_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(seed_);
       }
    }

    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void setSeed(
        int index, org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSeedIsMutable();
      seed_.set(index, value);
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void setSeed(
        int index, org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
      ensureSeedIsMutable();
      seed_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSeedIsMutable();
      seed_.add(value);
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(
        int index, org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureSeedIsMutable();
      seed_.add(index, value);
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(
        org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
      ensureSeedIsMutable();
      seed_.add(builderForValue.build());
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void addSeed(
        int index, org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
      ensureSeedIsMutable();
      seed_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void addAllSeed(
        java.lang.Iterable<? extends org.flo.crawler.PeerSeedProtos.PeerSeedData> values) {
      ensureSeedIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, seed_);
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void clearSeed() {
      seed_ = emptyProtobufList();
    }
    /**
     * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
     */
    private void removeSeed(int index) {
      ensureSeedIsMutable();
      seed_.remove(index);
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    private void setTimestamp(long value) {
      bitField0_ |= 0x00000001;
      timestamp_ = value;
    }
    /**
     * <pre>
     * seconds since UNIX epoch
     * </pre>
     *
     * <code>required uint64 timestamp = 2;</code>
     */
    private void clearTimestamp() {
      bitField0_ = (bitField0_ & ~0x00000001);
      timestamp_ = 0L;
    }

    public static final int NET_FIELD_NUMBER = 3;
    private java.lang.String net_;
    /**
     * <code>required string net = 3;</code>
     */
    public boolean hasNet() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string net = 3;</code>
     */
    public java.lang.String getNet() {
      return net_;
    }
    /**
     * <code>required string net = 3;</code>
     */
    public com.google.protobuf.ByteString
        getNetBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(net_);
    }
    /**
     * <code>required string net = 3;</code>
     */
    private void setNet(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      net_ = value;
    }
    /**
     * <code>required string net = 3;</code>
     */
    private void clearNet() {
      bitField0_ = (bitField0_ & ~0x00000002);
      net_ = getDefaultInstance().getNet();
    }
    /**
     * <code>required string net = 3;</code>
     */
    private void setNetBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      net_ = value.toStringUtf8();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < seed_.size(); i++) {
        output.writeMessage(1, seed_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeString(3, getNet());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < seed_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, seed_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNet());
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.PeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flo.crawler.PeerSeedProtos.PeerSeeds prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code org.flo.crawler.PeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.flo.crawler.PeerSeedProtos.PeerSeeds, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.flo.crawler.PeerSeeds)
        org.flo.crawler.PeerSeedProtos.PeerSeedsOrBuilder {
      // Construct using org.flo.crawler.PeerSeedProtos.PeerSeeds.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public java.util.List<org.flo.crawler.PeerSeedProtos.PeerSeedData> getSeedList() {
        return java.util.Collections.unmodifiableList(
            instance.getSeedList());
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public int getSeedCount() {
        return instance.getSeedCount();
      }/**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public org.flo.crawler.PeerSeedProtos.PeerSeedData getSeed(int index) {
        return instance.getSeed(index);
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.setSeed(index, value);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder setSeed(
          int index, org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.setSeed(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.addSeed(value);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.flo.crawler.PeerSeedProtos.PeerSeedData value) {
        copyOnWrite();
        instance.addSeed(index, value);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.addSeed(builderForValue);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addSeed(
          int index, org.flo.crawler.PeerSeedProtos.PeerSeedData.Builder builderForValue) {
        copyOnWrite();
        instance.addSeed(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder addAllSeed(
          java.lang.Iterable<? extends org.flo.crawler.PeerSeedProtos.PeerSeedData> values) {
        copyOnWrite();
        instance.addAllSeed(values);
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder clearSeed() {
        copyOnWrite();
        instance.clearSeed();
        return this;
      }
      /**
       * <code>repeated .org.flo.crawler.PeerSeedData seed = 1;</code>
       */
      public Builder removeSeed(int index) {
        copyOnWrite();
        instance.removeSeed(index);
        return this;
      }

      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       */
      public boolean hasTimestamp() {
        return instance.hasTimestamp();
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       */
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <pre>
       * seconds since UNIX epoch
       * </pre>
       *
       * <code>required uint64 timestamp = 2;</code>
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      /**
       * <code>required string net = 3;</code>
       */
      public boolean hasNet() {
        return instance.hasNet();
      }
      /**
       * <code>required string net = 3;</code>
       */
      public java.lang.String getNet() {
        return instance.getNet();
      }
      /**
       * <code>required string net = 3;</code>
       */
      public com.google.protobuf.ByteString
          getNetBytes() {
        return instance.getNetBytes();
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder setNet(
          java.lang.String value) {
        copyOnWrite();
        instance.setNet(value);
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder clearNet() {
        copyOnWrite();
        instance.clearNet();
        return this;
      }
      /**
       * <code>required string net = 3;</code>
       */
      public Builder setNetBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNetBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.flo.crawler.PeerSeeds)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.flo.crawler.PeerSeedProtos.PeerSeeds();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasTimestamp()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasNet()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          for (int i = 0; i < getSeedCount(); i++) {
            if (!getSeed(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          seed_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.flo.crawler.PeerSeedProtos.PeerSeeds other = (org.flo.crawler.PeerSeedProtos.PeerSeeds) arg1;
          seed_= visitor.visitList(seed_, other.seed_);
          timestamp_ = visitor.visitLong(
              hasTimestamp(), timestamp_,
              other.hasTimestamp(), other.timestamp_);
          net_ = visitor.visitString(
              hasNet(), net_,
              other.hasNet(), other.net_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!seed_.isModifiable()) {
                    seed_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(seed_);
                  }
                  seed_.add(
                      input.readMessage(org.flo.crawler.PeerSeedProtos.PeerSeedData.parser(), extensionRegistry));
                  break;
                }
                case 16: {
                  bitField0_ |= 0x00000001;
                  timestamp_ = input.readUInt64();
                  break;
                }
                case 26: {
                  String s = input.readString();
                  bitField0_ |= 0x00000002;
                  net_ = s;
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.flo.crawler.PeerSeedProtos.PeerSeeds.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.flo.crawler.PeerSeeds)
    private static final org.flo.crawler.PeerSeedProtos.PeerSeeds DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new PeerSeeds();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.flo.crawler.PeerSeedProtos.PeerSeeds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<PeerSeeds> PARSER;

    public static com.google.protobuf.Parser<PeerSeeds> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SignedPeerSeedsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.flo.crawler.SignedPeerSeeds)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    boolean hasPeerSeeds();
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    com.google.protobuf.ByteString getPeerSeeds();

    /**
     * <code>required bytes signature = 2;</code>
     */
    boolean hasSignature();
    /**
     * <code>required bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <code>required bytes pubkey = 3;</code>
     */
    boolean hasPubkey();
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    com.google.protobuf.ByteString getPubkey();
  }
  /**
   * Protobuf type {@code org.flo.crawler.SignedPeerSeeds}
   */
  public  static final class SignedPeerSeeds extends
      com.google.protobuf.GeneratedMessageLite<
          SignedPeerSeeds, SignedPeerSeeds.Builder> implements
      // @@protoc_insertion_point(message_implements:org.flo.crawler.SignedPeerSeeds)
      SignedPeerSeedsOrBuilder {
    private SignedPeerSeeds() {
      peerSeeds_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      pubkey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int PEER_SEEDS_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString peerSeeds_;
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    public boolean hasPeerSeeds() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    public com.google.protobuf.ByteString getPeerSeeds() {
      return peerSeeds_;
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    private void setPeerSeeds(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
      peerSeeds_ = value;
    }
    /**
     * <code>required bytes peer_seeds = 1;</code>
     */
    private void clearPeerSeeds() {
      bitField0_ = (bitField0_ & ~0x00000001);
      peerSeeds_ = getDefaultInstance().getPeerSeeds();
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <code>required bytes signature = 2;</code>
     */
    public boolean hasSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    private void setSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      signature_ = value;
    }
    /**
     * <code>required bytes signature = 2;</code>
     */
    private void clearSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      signature_ = getDefaultInstance().getSignature();
    }

    public static final int PUBKEY_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString pubkey_;
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    public boolean hasPubkey() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    public com.google.protobuf.ByteString getPubkey() {
      return pubkey_;
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    private void setPubkey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
      pubkey_ = value;
    }
    /**
     * <code>required bytes pubkey = 3;</code>
     */
    private void clearPubkey() {
      bitField0_ = (bitField0_ & ~0x00000004);
      pubkey_ = getDefaultInstance().getPubkey();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, peerSeeds_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, pubkey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, peerSeeds_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, pubkey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flo.crawler.PeerSeedProtos.SignedPeerSeeds prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * Protobuf type {@code org.flo.crawler.SignedPeerSeeds}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.flo.crawler.PeerSeedProtos.SignedPeerSeeds, Builder> implements
        // @@protoc_insertion_point(builder_implements:org.flo.crawler.SignedPeerSeeds)
        org.flo.crawler.PeerSeedProtos.SignedPeerSeedsOrBuilder {
      // Construct using org.flo.crawler.PeerSeedProtos.SignedPeerSeeds.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public boolean hasPeerSeeds() {
        return instance.hasPeerSeeds();
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public com.google.protobuf.ByteString getPeerSeeds() {
        return instance.getPeerSeeds();
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public Builder setPeerSeeds(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPeerSeeds(value);
        return this;
      }
      /**
       * <code>required bytes peer_seeds = 1;</code>
       */
      public Builder clearPeerSeeds() {
        copyOnWrite();
        instance.clearPeerSeeds();
        return this;
      }

      /**
       * <code>required bytes signature = 2;</code>
       */
      public boolean hasSignature() {
        return instance.hasSignature();
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return instance.getSignature();
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSignature(value);
        return this;
      }
      /**
       * <code>required bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        copyOnWrite();
        instance.clearSignature();
        return this;
      }

      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public boolean hasPubkey() {
        return instance.hasPubkey();
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public com.google.protobuf.ByteString getPubkey() {
        return instance.getPubkey();
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public Builder setPubkey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPubkey(value);
        return this;
      }
      /**
       * <code>required bytes pubkey = 3;</code>
       */
      public Builder clearPubkey() {
        copyOnWrite();
        instance.clearPubkey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:org.flo.crawler.SignedPeerSeeds)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.flo.crawler.PeerSeedProtos.SignedPeerSeeds();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasPeerSeeds()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasSignature()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasPubkey()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.flo.crawler.PeerSeedProtos.SignedPeerSeeds other = (org.flo.crawler.PeerSeedProtos.SignedPeerSeeds) arg1;
          peerSeeds_ = visitor.visitByteString(
              hasPeerSeeds(), peerSeeds_,
              other.hasPeerSeeds(), other.peerSeeds_);
          signature_ = visitor.visitByteString(
              hasSignature(), signature_,
              other.hasSignature(), other.signature_);
          pubkey_ = visitor.visitByteString(
              hasPubkey(), pubkey_,
              other.hasPubkey(), other.pubkey_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  bitField0_ |= 0x00000001;
                  peerSeeds_ = input.readBytes();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  signature_ = input.readBytes();
                  break;
                }
                case 26: {
                  bitField0_ |= 0x00000004;
                  pubkey_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.flo.crawler.PeerSeedProtos.SignedPeerSeeds.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:org.flo.crawler.SignedPeerSeeds)
    private static final org.flo.crawler.PeerSeedProtos.SignedPeerSeeds DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new SignedPeerSeeds();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.flo.crawler.PeerSeedProtos.SignedPeerSeeds getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SignedPeerSeeds> PARSER;

    public static com.google.protobuf.Parser<SignedPeerSeeds> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
