// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: storedserverpaymentchannel.proto

package org.floj.protocols.channels;

public final class ServerState {
  private ServerState() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface StoredServerPaymentChannelsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredServerPaymentChannels)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    java.util.List<org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> 
        getChannelsList();
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    org.floj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index);
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    int getChannelsCount();
  }
  /**
   * <pre>
   * A set of StoredPaymentChannel's
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredServerPaymentChannels}
   */
  public  static final class StoredServerPaymentChannels extends
      com.google.protobuf.GeneratedMessageLite<
          StoredServerPaymentChannels, StoredServerPaymentChannels.Builder> implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredServerPaymentChannels)
      StoredServerPaymentChannelsOrBuilder {
    private StoredServerPaymentChannels() {
      channels_ = emptyProtobufList();
    }
    public static final int CHANNELS_FIELD_NUMBER = 1;
    private com.google.protobuf.Internal.ProtobufList<org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> channels_;
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public java.util.List<org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> getChannelsList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public java.util.List<? extends org.floj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder> 
        getChannelsOrBuilderList() {
      return channels_;
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public int getChannelsCount() {
      return channels_.size();
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public org.floj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index) {
      return channels_.get(index);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    public org.floj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder getChannelsOrBuilder(
        int index) {
      return channels_.get(index);
    }
    private void ensureChannelsIsMutable() {
      if (!channels_.isModifiable()) {
        channels_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(channels_);
       }
    }

    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void setChannels(
        int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureChannelsIsMutable();
      channels_.set(index, value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void setChannels(
        int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
      ensureChannelsIsMutable();
      channels_.set(index, builderForValue.build());
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureChannelsIsMutable();
      channels_.add(value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(
        int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
      if (value == null) {
        throw new NullPointerException();
      }
      ensureChannelsIsMutable();
      channels_.add(index, value);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(
        org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
      ensureChannelsIsMutable();
      channels_.add(builderForValue.build());
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addChannels(
        int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
      ensureChannelsIsMutable();
      channels_.add(index, builderForValue.build());
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void addAllChannels(
        java.lang.Iterable<? extends org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> values) {
      ensureChannelsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, channels_);
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void clearChannels() {
      channels_ = emptyProtobufList();
    }
    /**
     * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
     */
    private void removeChannels(int index) {
      ensureChannelsIsMutable();
      channels_.remove(index);
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < channels_.size(); i++) {
        output.writeMessage(1, channels_.get(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < channels_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, channels_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.floj.protocols.channels.ServerState.StoredServerPaymentChannels prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * A set of StoredPaymentChannel's
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredServerPaymentChannels}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.floj.protocols.channels.ServerState.StoredServerPaymentChannels, Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredServerPaymentChannels)
        org.floj.protocols.channels.ServerState.StoredServerPaymentChannelsOrBuilder {
      // Construct using org.floj.protocols.channels.ServerState.StoredServerPaymentChannels.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public java.util.List<org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> getChannelsList() {
        return java.util.Collections.unmodifiableList(
            instance.getChannelsList());
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public int getChannelsCount() {
        return instance.getChannelsCount();
      }/**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public org.floj.protocols.channels.ServerState.StoredServerPaymentChannel getChannels(int index) {
        return instance.getChannels(index);
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.setChannels(index, value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder setChannels(
          int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.setChannels(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.addChannels(value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel value) {
        copyOnWrite();
        instance.addChannels(index, value);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.addChannels(builderForValue);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addChannels(
          int index, org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.Builder builderForValue) {
        copyOnWrite();
        instance.addChannels(index, builderForValue);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder addAllChannels(
          java.lang.Iterable<? extends org.floj.protocols.channels.ServerState.StoredServerPaymentChannel> values) {
        copyOnWrite();
        instance.addAllChannels(values);
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder clearChannels() {
        copyOnWrite();
        instance.clearChannels();
        return this;
      }
      /**
       * <code>repeated .paymentchannels.StoredServerPaymentChannel channels = 1;</code>
       */
      public Builder removeChannels(int index) {
        copyOnWrite();
        instance.removeChannels(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredServerPaymentChannels)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.floj.protocols.channels.ServerState.StoredServerPaymentChannels();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          for (int i = 0; i < getChannelsCount(); i++) {
            if (!getChannels(i).isInitialized()) {
              if (shouldMemoize) {
                memoizedIsInitialized = 0;
              }
              return null;
            }
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          channels_.makeImmutable();
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.floj.protocols.channels.ServerState.StoredServerPaymentChannels other = (org.floj.protocols.channels.ServerState.StoredServerPaymentChannels) arg1;
          channels_= visitor.visitList(channels_, other.channels_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 10: {
                  if (!channels_.isModifiable()) {
                    channels_ =
                        com.google.protobuf.GeneratedMessageLite.mutableCopy(channels_);
                  }
                  channels_.add(
                      input.readMessage(org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.parser(), extensionRegistry));
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.floj.protocols.channels.ServerState.StoredServerPaymentChannels.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:paymentchannels.StoredServerPaymentChannels)
    private static final org.floj.protocols.channels.ServerState.StoredServerPaymentChannels DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StoredServerPaymentChannels();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannels getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StoredServerPaymentChannels> PARSER;

    public static com.google.protobuf.Parser<StoredServerPaymentChannels> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface StoredServerPaymentChannelOrBuilder extends
      // @@protoc_insertion_point(interface_extends:paymentchannels.StoredServerPaymentChannel)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    boolean hasBestValueToMe();
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    long getBestValueToMe();

    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    boolean hasBestValueSignature();
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    com.google.protobuf.ByteString getBestValueSignature();

    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    boolean hasRefundTransactionUnlockTimeSecs();
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    long getRefundTransactionUnlockTimeSecs();

    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    boolean hasContractTransaction();
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    com.google.protobuf.ByteString getContractTransaction();

    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    boolean hasClientOutput();
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    com.google.protobuf.ByteString getClientOutput();

    /**
     * <code>required bytes myKey = 6;</code>
     */
    boolean hasMyKey();
    /**
     * <code>required bytes myKey = 6;</code>
     */
    com.google.protobuf.ByteString getMyKey();

    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    boolean hasMajorVersion();
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    int getMajorVersion();

    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    boolean hasClientKey();
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    com.google.protobuf.ByteString getClientKey();
  }
  /**
   * <pre>
   * A server-side payment channel in serialized form, which can be reloaded later if the server restarts
   * </pre>
   *
   * Protobuf type {@code paymentchannels.StoredServerPaymentChannel}
   */
  public  static final class StoredServerPaymentChannel extends
      com.google.protobuf.GeneratedMessageLite<
          StoredServerPaymentChannel, StoredServerPaymentChannel.Builder> implements
      // @@protoc_insertion_point(message_implements:paymentchannels.StoredServerPaymentChannel)
      StoredServerPaymentChannelOrBuilder {
    private StoredServerPaymentChannel() {
      bestValueSignature_ = com.google.protobuf.ByteString.EMPTY;
      contractTransaction_ = com.google.protobuf.ByteString.EMPTY;
      clientOutput_ = com.google.protobuf.ByteString.EMPTY;
      myKey_ = com.google.protobuf.ByteString.EMPTY;
      majorVersion_ = 1;
      clientKey_ = com.google.protobuf.ByteString.EMPTY;
    }
    private int bitField0_;
    public static final int BESTVALUETOME_FIELD_NUMBER = 1;
    private long bestValueToMe_;
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    public boolean hasBestValueToMe() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    public long getBestValueToMe() {
      return bestValueToMe_;
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    private void setBestValueToMe(long value) {
      bitField0_ |= 0x00000001;
      bestValueToMe_ = value;
    }
    /**
     * <code>required uint64 bestValueToMe = 1;</code>
     */
    private void clearBestValueToMe() {
      bitField0_ = (bitField0_ & ~0x00000001);
      bestValueToMe_ = 0L;
    }

    public static final int BESTVALUESIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString bestValueSignature_;
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    public boolean hasBestValueSignature() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    public com.google.protobuf.ByteString getBestValueSignature() {
      return bestValueSignature_;
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    private void setBestValueSignature(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
      bestValueSignature_ = value;
    }
    /**
     * <code>optional bytes bestValueSignature = 2;</code>
     */
    private void clearBestValueSignature() {
      bitField0_ = (bitField0_ & ~0x00000002);
      bestValueSignature_ = getDefaultInstance().getBestValueSignature();
    }

    public static final int REFUNDTRANSACTIONUNLOCKTIMESECS_FIELD_NUMBER = 3;
    private long refundTransactionUnlockTimeSecs_;
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    public boolean hasRefundTransactionUnlockTimeSecs() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    public long getRefundTransactionUnlockTimeSecs() {
      return refundTransactionUnlockTimeSecs_;
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    private void setRefundTransactionUnlockTimeSecs(long value) {
      bitField0_ |= 0x00000004;
      refundTransactionUnlockTimeSecs_ = value;
    }
    /**
     * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
     */
    private void clearRefundTransactionUnlockTimeSecs() {
      bitField0_ = (bitField0_ & ~0x00000004);
      refundTransactionUnlockTimeSecs_ = 0L;
    }

    public static final int CONTRACTTRANSACTION_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString contractTransaction_;
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    public boolean hasContractTransaction() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    public com.google.protobuf.ByteString getContractTransaction() {
      return contractTransaction_;
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    private void setContractTransaction(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
      contractTransaction_ = value;
    }
    /**
     * <code>required bytes contractTransaction = 4;</code>
     */
    private void clearContractTransaction() {
      bitField0_ = (bitField0_ & ~0x00000008);
      contractTransaction_ = getDefaultInstance().getContractTransaction();
    }

    public static final int CLIENTOUTPUT_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString clientOutput_;
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    public boolean hasClientOutput() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    public com.google.protobuf.ByteString getClientOutput() {
      return clientOutput_;
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    private void setClientOutput(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
      clientOutput_ = value;
    }
    /**
     * <code>optional bytes clientOutput = 5;</code>
     */
    private void clearClientOutput() {
      bitField0_ = (bitField0_ & ~0x00000010);
      clientOutput_ = getDefaultInstance().getClientOutput();
    }

    public static final int MYKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString myKey_;
    /**
     * <code>required bytes myKey = 6;</code>
     */
    public boolean hasMyKey() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required bytes myKey = 6;</code>
     */
    public com.google.protobuf.ByteString getMyKey() {
      return myKey_;
    }
    /**
     * <code>required bytes myKey = 6;</code>
     */
    private void setMyKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
      myKey_ = value;
    }
    /**
     * <code>required bytes myKey = 6;</code>
     */
    private void clearMyKey() {
      bitField0_ = (bitField0_ & ~0x00000020);
      myKey_ = getDefaultInstance().getMyKey();
    }

    public static final int MAJORVERSION_FIELD_NUMBER = 7;
    private int majorVersion_;
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    public boolean hasMajorVersion() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    public int getMajorVersion() {
      return majorVersion_;
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    private void setMajorVersion(int value) {
      bitField0_ |= 0x00000040;
      majorVersion_ = value;
    }
    /**
     * <code>optional uint32 majorVersion = 7 [default = 1];</code>
     */
    private void clearMajorVersion() {
      bitField0_ = (bitField0_ & ~0x00000040);
      majorVersion_ = 1;
    }

    public static final int CLIENTKEY_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString clientKey_;
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    public boolean hasClientKey() {
      return ((bitField0_ & 0x00000080) == 0x00000080);
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    public com.google.protobuf.ByteString getClientKey() {
      return clientKey_;
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    private void setClientKey(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000080;
      clientKey_ = value;
    }
    /**
     * <pre>
     * Protocol version 2 only - the P2SH hash doesn't contain the required key
     * </pre>
     *
     * <code>optional bytes clientKey = 8;</code>
     */
    private void clearClientKey() {
      bitField0_ = (bitField0_ & ~0x00000080);
      clientKey_ = getDefaultInstance().getClientKey();
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt64(1, bestValueToMe_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, bestValueSignature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeUInt64(3, refundTransactionUnlockTimeSecs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, contractTransaction_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, clientOutput_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, myKey_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeUInt32(7, majorVersion_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        output.writeBytes(8, clientKey_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, bestValueToMe_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, bestValueSignature_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, refundTransactionUnlockTimeSecs_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, contractTransaction_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, clientOutput_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, myKey_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(7, majorVersion_);
      }
      if (((bitField0_ & 0x00000080) == 0x00000080)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, clientKey_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.floj.protocols.channels.ServerState.StoredServerPaymentChannel prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    /**
     * <pre>
     * A server-side payment channel in serialized form, which can be reloaded later if the server restarts
     * </pre>
     *
     * Protobuf type {@code paymentchannels.StoredServerPaymentChannel}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          org.floj.protocols.channels.ServerState.StoredServerPaymentChannel, Builder> implements
        // @@protoc_insertion_point(builder_implements:paymentchannels.StoredServerPaymentChannel)
        org.floj.protocols.channels.ServerState.StoredServerPaymentChannelOrBuilder {
      // Construct using org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       */
      public boolean hasBestValueToMe() {
        return instance.hasBestValueToMe();
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       */
      public long getBestValueToMe() {
        return instance.getBestValueToMe();
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       */
      public Builder setBestValueToMe(long value) {
        copyOnWrite();
        instance.setBestValueToMe(value);
        return this;
      }
      /**
       * <code>required uint64 bestValueToMe = 1;</code>
       */
      public Builder clearBestValueToMe() {
        copyOnWrite();
        instance.clearBestValueToMe();
        return this;
      }

      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       */
      public boolean hasBestValueSignature() {
        return instance.hasBestValueSignature();
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       */
      public com.google.protobuf.ByteString getBestValueSignature() {
        return instance.getBestValueSignature();
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       */
      public Builder setBestValueSignature(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setBestValueSignature(value);
        return this;
      }
      /**
       * <code>optional bytes bestValueSignature = 2;</code>
       */
      public Builder clearBestValueSignature() {
        copyOnWrite();
        instance.clearBestValueSignature();
        return this;
      }

      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       */
      public boolean hasRefundTransactionUnlockTimeSecs() {
        return instance.hasRefundTransactionUnlockTimeSecs();
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       */
      public long getRefundTransactionUnlockTimeSecs() {
        return instance.getRefundTransactionUnlockTimeSecs();
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       */
      public Builder setRefundTransactionUnlockTimeSecs(long value) {
        copyOnWrite();
        instance.setRefundTransactionUnlockTimeSecs(value);
        return this;
      }
      /**
       * <code>required uint64 refundTransactionUnlockTimeSecs = 3;</code>
       */
      public Builder clearRefundTransactionUnlockTimeSecs() {
        copyOnWrite();
        instance.clearRefundTransactionUnlockTimeSecs();
        return this;
      }

      /**
       * <code>required bytes contractTransaction = 4;</code>
       */
      public boolean hasContractTransaction() {
        return instance.hasContractTransaction();
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       */
      public com.google.protobuf.ByteString getContractTransaction() {
        return instance.getContractTransaction();
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       */
      public Builder setContractTransaction(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContractTransaction(value);
        return this;
      }
      /**
       * <code>required bytes contractTransaction = 4;</code>
       */
      public Builder clearContractTransaction() {
        copyOnWrite();
        instance.clearContractTransaction();
        return this;
      }

      /**
       * <code>optional bytes clientOutput = 5;</code>
       */
      public boolean hasClientOutput() {
        return instance.hasClientOutput();
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       */
      public com.google.protobuf.ByteString getClientOutput() {
        return instance.getClientOutput();
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       */
      public Builder setClientOutput(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientOutput(value);
        return this;
      }
      /**
       * <code>optional bytes clientOutput = 5;</code>
       */
      public Builder clearClientOutput() {
        copyOnWrite();
        instance.clearClientOutput();
        return this;
      }

      /**
       * <code>required bytes myKey = 6;</code>
       */
      public boolean hasMyKey() {
        return instance.hasMyKey();
      }
      /**
       * <code>required bytes myKey = 6;</code>
       */
      public com.google.protobuf.ByteString getMyKey() {
        return instance.getMyKey();
      }
      /**
       * <code>required bytes myKey = 6;</code>
       */
      public Builder setMyKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMyKey(value);
        return this;
      }
      /**
       * <code>required bytes myKey = 6;</code>
       */
      public Builder clearMyKey() {
        copyOnWrite();
        instance.clearMyKey();
        return this;
      }

      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       */
      public boolean hasMajorVersion() {
        return instance.hasMajorVersion();
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       */
      public int getMajorVersion() {
        return instance.getMajorVersion();
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       */
      public Builder setMajorVersion(int value) {
        copyOnWrite();
        instance.setMajorVersion(value);
        return this;
      }
      /**
       * <code>optional uint32 majorVersion = 7 [default = 1];</code>
       */
      public Builder clearMajorVersion() {
        copyOnWrite();
        instance.clearMajorVersion();
        return this;
      }

      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       */
      public boolean hasClientKey() {
        return instance.hasClientKey();
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       */
      public com.google.protobuf.ByteString getClientKey() {
        return instance.getClientKey();
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       */
      public Builder setClientKey(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setClientKey(value);
        return this;
      }
      /**
       * <pre>
       * Protocol version 2 only - the P2SH hash doesn't contain the required key
       * </pre>
       *
       * <code>optional bytes clientKey = 8;</code>
       */
      public Builder clearClientKey() {
        copyOnWrite();
        instance.clearClientKey();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:paymentchannels.StoredServerPaymentChannel)
    }
    private byte memoizedIsInitialized = -1;
    protected final Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new org.floj.protocols.channels.ServerState.StoredServerPaymentChannel();
        }
        case IS_INITIALIZED: {
          byte isInitialized = memoizedIsInitialized;
          if (isInitialized == 1) return DEFAULT_INSTANCE;
          if (isInitialized == 0) return null;

          boolean shouldMemoize = ((Boolean) arg0).booleanValue();
          if (!hasBestValueToMe()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasRefundTransactionUnlockTimeSecs()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasContractTransaction()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (!hasMyKey()) {
            if (shouldMemoize) {
              memoizedIsInitialized = 0;
            }
            return null;
          }
          if (shouldMemoize) memoizedIsInitialized = 1;
          return DEFAULT_INSTANCE;

        }
        case MAKE_IMMUTABLE: {
          return null;
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case VISIT: {
          Visitor visitor = (Visitor) arg0;
          org.floj.protocols.channels.ServerState.StoredServerPaymentChannel other = (org.floj.protocols.channels.ServerState.StoredServerPaymentChannel) arg1;
          bestValueToMe_ = visitor.visitLong(
              hasBestValueToMe(), bestValueToMe_,
              other.hasBestValueToMe(), other.bestValueToMe_);
          bestValueSignature_ = visitor.visitByteString(
              hasBestValueSignature(), bestValueSignature_,
              other.hasBestValueSignature(), other.bestValueSignature_);
          refundTransactionUnlockTimeSecs_ = visitor.visitLong(
              hasRefundTransactionUnlockTimeSecs(), refundTransactionUnlockTimeSecs_,
              other.hasRefundTransactionUnlockTimeSecs(), other.refundTransactionUnlockTimeSecs_);
          contractTransaction_ = visitor.visitByteString(
              hasContractTransaction(), contractTransaction_,
              other.hasContractTransaction(), other.contractTransaction_);
          clientOutput_ = visitor.visitByteString(
              hasClientOutput(), clientOutput_,
              other.hasClientOutput(), other.clientOutput_);
          myKey_ = visitor.visitByteString(
              hasMyKey(), myKey_,
              other.hasMyKey(), other.myKey_);
          majorVersion_ = visitor.visitInt(
              hasMajorVersion(), majorVersion_,
              other.hasMajorVersion(), other.majorVersion_);
          clientKey_ = visitor.visitByteString(
              hasClientKey(), clientKey_,
              other.hasClientKey(), other.clientKey_);
          if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
              .INSTANCE) {
            bitField0_ |= other.bitField0_;
          }
          return this;
        }
        case MERGE_FROM_STREAM: {
          com.google.protobuf.CodedInputStream input =
              (com.google.protobuf.CodedInputStream) arg0;
          com.google.protobuf.ExtensionRegistryLite extensionRegistry =
              (com.google.protobuf.ExtensionRegistryLite) arg1;
          try {
            boolean done = false;
            while (!done) {
              int tag = input.readTag();
              switch (tag) {
                case 0:
                  done = true;
                  break;
                default: {
                  if (!parseUnknownField(tag, input)) {
                    done = true;
                  }
                  break;
                }
                case 8: {
                  bitField0_ |= 0x00000001;
                  bestValueToMe_ = input.readUInt64();
                  break;
                }
                case 18: {
                  bitField0_ |= 0x00000002;
                  bestValueSignature_ = input.readBytes();
                  break;
                }
                case 24: {
                  bitField0_ |= 0x00000004;
                  refundTransactionUnlockTimeSecs_ = input.readUInt64();
                  break;
                }
                case 34: {
                  bitField0_ |= 0x00000008;
                  contractTransaction_ = input.readBytes();
                  break;
                }
                case 42: {
                  bitField0_ |= 0x00000010;
                  clientOutput_ = input.readBytes();
                  break;
                }
                case 50: {
                  bitField0_ |= 0x00000020;
                  myKey_ = input.readBytes();
                  break;
                }
                case 56: {
                  bitField0_ |= 0x00000040;
                  majorVersion_ = input.readUInt32();
                  break;
                }
                case 66: {
                  bitField0_ |= 0x00000080;
                  clientKey_ = input.readBytes();
                  break;
                }
              }
            }
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw new RuntimeException(e.setUnfinishedMessage(this));
          } catch (java.io.IOException e) {
            throw new RuntimeException(
                new com.google.protobuf.InvalidProtocolBufferException(
                    e.getMessage()).setUnfinishedMessage(this));
          } finally {
          }
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          if (PARSER == null) {    synchronized (org.floj.protocols.channels.ServerState.StoredServerPaymentChannel.class) {
              if (PARSER == null) {
                PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
              }
            }
          }
          return PARSER;
        }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:paymentchannels.StoredServerPaymentChannel)
    private static final org.floj.protocols.channels.ServerState.StoredServerPaymentChannel DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new StoredServerPaymentChannel();
      DEFAULT_INSTANCE.makeImmutable();
    }

    public static org.floj.protocols.channels.ServerState.StoredServerPaymentChannel getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<StoredServerPaymentChannel> PARSER;

    public static com.google.protobuf.Parser<StoredServerPaymentChannel> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
